name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  jvm:
    strategy:
      fail-fast: false
      matrix:
        java: [11, 8]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
      - run: sbt +testsJVM/test plugin/test
        env:
          GOOGLE_APPLICATION_CREDENTIALS:
            ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          GOOGLE_APPLICATION_CREDENTIALS_JSON:
            ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
  js:
    strategy:
      fail-fast: false
      matrix:
        scalajs: ["1.1.1", "0.6.32"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
      - run: sbt +testsJS/test
        env:
          SCALAJS_VERSION: ${{ matrix.scalajs }}
          GOOGLE_APPLICATION_CREDENTIALS:
            ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          GOOGLE_APPLICATION_CREDENTIALS_JSON:
            ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
  native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
      - run: sbt +testsNative/test
        env:
          GOOGLE_APPLICATION_CREDENTIALS:
            ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          GOOGLE_APPLICATION_CREDENTIALS_JSON:
            ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
      - run: csbt +testsJVM/test
        shell: bash
        env:
          GOOGLE_APPLICATION_CREDENTIALS:
            ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          GOOGLE_APPLICATION_CREDENTIALS_JSON:
            ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
      - run: ./bin/scalafmt --check
      - run: sbt scalafixAll
      - run: sbt docs/docusaurusCreateSite
        env:
          GOOGLE_APPLICATION_CREDENTIALS:
            ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          GOOGLE_APPLICATION_CREDENTIALS_JSON:
            ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
